# Generated by Django 5.2.5 on 2025-10-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electrónica'), ('fashion', 'Moda y Ropa'), ('home', 'Hogar y Jardín'), ('sports', 'Deportes'), ('books', 'Libros'), ('toys', 'Juguetes'), ('beauty', 'Belleza y Cuidado Personal'), ('automotive', 'Automotriz'), ('food', 'Alimentos y Bebidas'), ('other', 'Otros')], default='other', max_length=50),
        ),
    ]
